id: article_writing
name: 최신 기사 작성
description: 선택한 토픽에 대한 최신 정보를 수집하여 기사를 작성합니다.

tasks:
  - id: keyword_extraction
    handler: ai_process
    parameters:
      prompt_template: keyword_extraction/news_keywords
      input_from: user_input
      output_format: json
      
  - id: search_info
    handler: brave_search
    parameters:
      query_from: keyword_extraction
      count: 17
      time_range: "3d"
      sort: "recent"
      
  - id: fetch_related_articles
    handler: rss_related_fetch
    parameters:
      keywords_from: keyword_extraction
      sources:
        - https://news.google.com/rss?hl=ko&gl=KR&ceid=KR:ko
        - https://news.naver.com/main/rss/today/politics.xml
      max_per_source: 5
      
  - id: article_generation
    handler: ai_process
    parameters:
      prompt_template: article_generation/news
      inputs:
        - topic: user_input
        - search_results: search_info
        - related_articles: fetch_related_articles
      output_format: markdown
      
  - id: user_review
    handler: user_interaction
    parameters:
      type: text_editor
      data_from: article_generation
      title: "생성된 기사를 검토하고 편집하세요"
      
  - id: article_finalization
    handler: ai_process
    parameters:
      prompt_template: editing/finalize_article
      inputs:
        - original: article_generation
        - edited: user_review
      output_format: markdown 