id: content_generation_workflow
name: Content Generation and Translation
description: Generate text content and translate it to another language

tasks:
  - id: generate_content
    handler: generate_text
    parameters:
      prompt: "Write a short article about sustainable living and eco-friendly practices"
      length: 500

  - id: translate_to_spanish
    handler: translate_text
    parameters:
      previous_result: $generate_content
      target_language: "es"

  - id: save_both_versions
    handler: save_to_file
    parameters:
      filename: "sustainable_living_bilingual.txt"
      content: "$generate_content.text\n\n=== SPANISH TRANSLATION ===\n\n$translate_to_spanish.translated_text"
      format: "txt" 