id: news_crawling
name: 뉴스 크롤링 및 토픽 추출
description: RSS 피드에서 최신 뉴스를 수집하고 주요 토픽을 추출합니다.

tasks:
  - id: rss_crawling
    handler: rss_crawl
    parameters:
      sources:
        - https://news.google.com/rss?hl=ko&gl=KR&ceid=KR:ko
        - https://news.naver.com/main/rss/today/politics.xml
        - https://news.naver.com/main/rss/today/economy.xml
        - https://news.naver.com/main/rss/today/society.xml
        - https://news.naver.com/main/rss/today/it_secience.xml
      time_range_days: 3
      
  - id: topic_extraction
    handler: ai_process
    parameters:
      prompt_template: topic_extraction/trending_topics
      input_from: rss_crawling
      output_format: json
      
  - id: user_selection
    handler: user_interaction
    parameters:
      type: checkbox_list
      data_from: topic_extraction
      title: "추출된 토픽 중 관심 있는 주제를 선택하세요" 